apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: websocket-operator-webhook
webhooks:
- name: websocket.operator.io
  sideEffects: None
  admissionReviewVersions: ["v1"]
  clientConfig:
    service:
      name: websocket-operator-webhook
      namespace: websocket-system
      path: "/mutate"
      port: 443
    caBundle: ${CA_BUNDLE}
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["apps"]
    apiVersions: ["v1"]
    resources: ["deployments"]
  failurePolicy: Fail
  namespaceSelector:
    matchExpressions:
    - key: websocket-operator-injection
      operator: NotIn
      values: ["disabled"]