name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        cache: true # Let the action handle caching automatically

    - name: Run go mod tidy
      run: |
        go mod tidy
        if [ -n "$(git diff go.mod go.sum)" ]; then
          echo "go.mod or go.sum is not up to date. Please run 'go mod tidy' locally and commit the changes."
          git diff go.mod go.sum
          exit 1
        fi

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...

    - name: Run vet
      run: go vet ./...

  build-loadbalancer:
    name: Build Loadbalancer Container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Loadbalancer Container
      run: make build-loadbalancer

  build-sidecar:
    name: Build Sidecar Container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Sidecar Container
      run: make build-sidecar

  build-operator:
    name: Build Operator Container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Operator Container
      run: make build-operator

